name: first_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: "^3.7.0"

dependencies:
  flutter:
    sdk: flutter
  process_run: ^0.13.0
  fluttertoast: ^8.2.4
  tray_manager: ^0.3.2
  bitsdojo_window: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
