name: goodnightpc
description: "GoodNightPC — Windows desktop app for scheduling shutdowns"
publish_to: 'none'
version: 1.1.0

environment:
  sdk: "^3.7.0"

dependencies:
  flutter:
    sdk: flutter
  process_run: ^0.13.0
  fluttertoast: ^8.2.4
  tray_manager: ^0.5.1
  bitsdojo_window: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.ico
    - assets/icon.png
    - assets/app_ico.ico
    - assets/app_ico.png
    - assets/yarlik.ico
    - assets/yarlik.png
